import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

import TopBar from "@/components/TopBar";
import SideBar from "@/components/SideBar";
import AppBar from '@mui/material/AppBar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Clevane Villareal | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col">
            <TopBar />
            <SideBar />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
